### ISSUE TITLE
Dependencies Download Issues on Mac on Travis

### ISSUE THREAD

**Issue by DavidMansolino** [cyberbotics/webots#1252]
**Describe the Bug**
In the mac test on Travis it often happens that one of the sumo, xc16 or ros dependencies fail to download, see for example: https://travis-ci.com/cyberbotics/webots/jobs/274046592#L3816

**Comment by omichel** [comment]
I believe I found the culprit: it's curl. It probably doesn't handle connection failures and retries as efficiently as wget does. So, since wget is already used in [Makefile.mac](https://github.com/cyberbotics/webots/blob/master/dependencies/Makefile.mac), I believe we should use it everywhere on mac. I am fixing this now.

**Comment by DavidMansolino** [comment]
Well spotted! This can indeed perfectly explain the difference.
