### ISSUE TITLE
From the point of (inverse dynamics) How can i know real torque 

### ISSUE THREAD

**Issue by rrkblee3** [cyberbotics/webots#1355]
(1) I made "2 link manipulator" because I have to experiment inverse dynamics test.
so i could get simulate torque was calculated by input angle. 
but it is not accurate. SO i wander if 'webots' can give me some method to get accurate torque, 
when i set my  motor parts by input angle

(2) When i set my motor with input angle. It was not coincide with real calculated angle 
     like this picture. how can i set my motor with input as it is.

 
![awfwfwafwf](https://user-images.githubusercontent.com/60958006/74333736-e26a1100-4ddb-11ea-9aa7-453ec23215f4.png)

**Comment by DavidMansolino** [comment]
Have you tried increasing the `maxVelocity` field of your motor?

**Comment by rrkblee3** [comment]
> d of your motor?

Yes but It was not coincide  real calculated angle and input angle still....

**Comment by DavidMansolino** [comment]
Would it be possible for you to share your simulation?

**Comment by rrkblee3** [comment]
> Would it be possible for you to share your simulation?
sure, thanks Mr.D  
[2LP.zip](https://github.com/cyberbotics/webots/files/4211419/2LP.zip)

**Comment by DavidMansolino** [comment]
Thank you, we will have a look at it and let you know here.

**Comment by DavidMansolino** [comment]
I checked your simulation, and the behavior you are observing looks normal for me, since you are constantly changing the target position, it is normal that the actual position is always 'late'.
If I set the target position to a fixed value, then after a transitional period (which is characteristic of any PID controller) the exact target value is reached.
If you want to get an exact and immediate match between your target and actual position, you have to do a kinematic simulation, but this will be way less realistic.
