### ISSUE TITLE
When launching Webots in a pipenv, it doesnt find python modules installed in that pipenv

### ISSUE THREAD

**Issue by RDaneelOlivav** [cyberbotics/webots#1485]
When launching webots installed through snap inside a pipenv with matplotlib installed,
when importing matplotlib in a controller python script, it doesnt find it.

**Steps to Reproduce**
pipenv shell
 webots

And the inside the webots simulation, in the controller python file:
import matplotlib
-->ModuleNotFoundError: No module named 'matplotlib'

Any Ideas on why this is happening and how to solve it?

**Comment by omichel** [comment]
Yes, this is because Webots uses the python installation built-in the snap package. If you want to use a different python installation (the one the system or from a pipenv), you should use extern robot controllers. This is explained [here](https://cyberbotics.com/doc/guide/running-extern-robot-controllers#running-extern-robot-controller-with-the-snap-version-of-webots). Setup of extern controllers is documented [here](https://cyberbotics.com/doc/guide/running-extern-robot-controllers#running-extern-robot-controller-with-the-snap-version-of-webots).
