### ISSUE TITLE
Bug in projects/samples/devices/worlds/pen.wbt 

### ISSUE THREAD

**Issue by chinakwy** [cyberbotics/webots#1529]
**Describe the Bug**
Hello, I'm using "pen" to draw trail. but I'm confused ,when I change the size of the arena, why does the trail  disappear and "pen" no longer draws trail ?
**Steps to Reproduce**
1. Go to 'projects/samples/devices/worlds/pen.wbt '
2. Click on 'RectangleArena (PROTO)'
3. Scroll down to 'floorSize'，and change it
4. See error：the trail  disappear and "pen" no longer draws trail

**Expected behavior**
the trail should be still there，and "pen" can continue draw trail

**Screenshots**
![image](https://user-images.githubusercontent.com/33207585/78762170-1e71ba80-79b6-11ea-9b35-b336e47de510.png)
![image](https://user-images.githubusercontent.com/33207585/78762237-33e6e480-79b6-11ea-8485-d707ce23a959.png)
**System**
 - Operating System: macOS Catalina
 - Graphics Card: Intel Iris Plus Graphics 640 1536 MB

**Additional context**

**Comment by omichel** [comment]
You should save the world after your change the size of the floor and reload it, so that the pen can work again with the resized floor. Let me know if that resolves the problem.

**Comment by chinakwy** [comment]
Hallo thanks for you reply

but it still works not well

 original 
![image](https://user-images.githubusercontent.com/33207585/79533656-f87da180-80aa-11ea-80e0-9d8e04130dd2.png)
when I change the size, it looks like below
![image](https://user-images.githubusercontent.com/33207585/79533606-db48d300-80aa-11ea-84ff-5c5fab548f44.png)

**Comment by omichel** [comment]
This is because should should also adjust the texture mapping of the floor when you change its size. The [Floor](https://github.com/cyberbotics/webots/blob/master/projects/objects/floors/protos/Floor.proto) PROTO doesn't handle this automatically because it uses repeating textures when scaled up. So when changing the `size` of this PROTO, you should also change the `tileSize` in the very same way, e.g., if you have `size 1 2`, you should also have `tileSize 1 2`. Similarly if you are using the [RectangleArena](https://github.com/cyberbotics/webots/blob/master/projects/objects/floors/protos/Floor.proto) PROTO, you should have matching `floorSize` and `floorTileSize`. You may need to create your own custom tile so that the floor resolution and content match your needs.

**Comment by chinakwy** [comment]
Thanks! It has done
