### ISSUE TITLE
Python rangeImageGetDepth Function Crashes

### ISSUE THREAD

**Issue by DavidMansolino** [cyberbotics/webots#1783]
**Describe the Bug**
The following controller makes the controller crash (can be tested with the 'range_ffinder.wbt' world):
```Python
from controller import Robot

robot = Robot()

timestep = int(robot.getBasicTimeStep())

range_finder = robot.getRangeFinder('range-finder')
range_finder.enable(timestep);

while robot.step(timestep) != -1:
    image = range_finder.getRangeImage()
    print(range_finder.rangeImageGetDepth(image, range_finder.getWidth(), 0, 0))
```

The crash, unfortunately, doesn't give any useful information (even in Python):
```
INFO: my_controller: Starting controller: python3.7 -u my_controller.py
WARNING: my_controller: The process crashed some time after starting successfully.
WARNING: 'my_controller' controller crashed
```

Tested both with Python 2.7 and 3.7

**Comment by stefaniapedrazzi** [comment]
It is like the call to `rangeImageGetDepth`, that returns a pointer to an object of the internal image list, corrupts some internal structure that make the controller crash during the next call of `getRangeImage`.

If I modify the `rangeImageGetDepth` function to return a double value instead of a PyObject or if I return a new `PyObject *` from the double value, then everything works fine.
This could be a workaround (or fix).

I'm now trying to better understand what is happening.
