### ISSUE TITLE
Physical collision plugin: Is there any exist Physics Plugin for detecting collision?

### ISSUE THREAD

**Issue by ipa-rwu** [cyberbotics/webots#1846]
Hello everyone,

I am wondering if there are any Physics Plugins for detecting collision?
For example, I have use case like this:
![webots](https://user-images.githubusercontent.com/54799760/86005047-6c75e780-ba14-11ea-83b1-9d9e012af5e7.png)

I want to have notification when the robot arm touches the table or box. But now I can see when it touches the table, it will just go through the table.  Is it possible?

Thanks in advance.

**Comment by omichel** [comment]
Normally your table should have a bounding object that prevents the robot from entering into it.
To detect collision of the robot with the table, I would recommend you to add a TouchSensor in the table.
In order to do this you should turn the table into a Robot and have this TouchSensor as a children of the table robot.
Then, from the controller of the table robot, you will be able to check for collisions.
You may also add TouchSensor nodes around the red baskets you put on the table if you want to detect collisions with the baskets.
Alternatively, you can also put TouchSensor nodes in the fingers of the gripper of the robot.
