### ISSUE TITLE
Rendering Devices not working in Asynchronous Mode

### ISSUE THREAD

**Issue by DavidMansolino** [cyberbotics/webots#1926]
**Describe the Bug**
There are some issues with rendering devices in asynchronous mode.

**Steps to Reproduce**
1. Open the camera.wbt world.
2. Set the 'synchronization' field of the robot to 'FALSE'.
3. Run the simulation in fast mode.
4. The controller displays some `Warning: wb_camera_get_image: image could not be retrieved.` warnings in the console and then crashes.

**Comment by stefaniapedrazzi** [comment]
The crash is simply due to the camera controller that doesn't check if the returned camera image is NULL and calls `wb_camera_image_get_reg` with a NULL value:
https://github.com/cyberbotics/webots/blob/cd3c191390786767c01ceb073f3326a0c4ce51db/include/controller/c/webots/camera.h#L79

The warning is printed because in fast mode the time step is increased while asking Webots the camera image, so the `current_time_step` stored just before remains one step back and doesn't match the `image_update_time`
https://github.com/cyberbotics/webots/blob/cd3c191390786767c01ceb073f3326a0c4ce51db/src/Controller/api/abstract_camera.c#L148-L150

`ac->image_update_time` doesn't match correctly time step at which the camera is requested but one step further.
However this doesn't seem a big problem, as this value is only used to check if the camera image is up-to-date.
So it seems quite safe to adapt the check in case of asynchronous mode.
