### ISSUE TITLE
[ROS]Time step service cannot be looped

### ISSUE THREAD

**Issue by Bingsheng1991** [cyberbotics/webots#2164]
**Describe the Bug**
I'm trying to control multiple epucks in Webos using ROS with changing wheel speeds. This requires time_step service to be called for each iteration in order to update actuator data. However, the service can only be called once (only the first speed takes affect), then it stops after one iteration.

**Expected behavior**
Update wheel speeds continuously under ROS

**System**
 - Operating System: Ubuntu 18.02
 - Graphics Card: Nvidia 2080 Super
 - Webots Version: R2020b

**Comment by DavidMansolino** [comment]
I just tried with a world with two e-pucks, everything seems to work as expected:
1. start roscore and the simulation => simulation runs
2. call once the step service for first e-puck: `rosservice call /epuck1/robot/time_step "{ value: 32 }"` => now simulation stops because robot 1 is waiting for new call to this service.
3. call the service every 1 second: `while true; do rosservice call /epuck1/robot/time_step "{ value: 32 }"; sleep 1; done` => now simulation runs again.
4. call once the step service for second e-puck: `rosservice call /epuck2/robot/time_step "{ value: 32 }"` => now simulation stops because robot 2 is waiting for new call to this service.
5. call the service every 1 second: `while true; do rosservice call /epuck2/robot/time_step "{ value: 32 }"; sleep 1; done` => now simulation runs again the service is called for both robots.

**Comment by omichel** [comment]
I am closing this issue. Feel free to re-open if needed.
