### ISSUE TITLE
UR10e collision bug

### ISSUE THREAD

**Issue by Simon-Steinmann** [cyberbotics/webots#2236]
There is a collision bug, when using self collision. The objects do not touch where it shows the collision points. I created a world showing the example. 
[ur10e_collisionbugwbt.zip](https://github.com/cyberbotics/webots/files/5212731/ur10e_collisionbugwbt.zip)

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/52213164/92996535-a8492500-f50c-11ea-929b-689a409ad5ca.gif)

**Comment by DavidMansolino** [comment]
There is indeed something wrong going out with this simulation, I can reproduce the issue too:

![ur10e_collisionbugwbt](https://user-images.githubusercontent.com/2461619/93050565-61ba0e80-f663-11ea-93b4-0acdbccc19ab.png)

**Comment by DavidMansolino** [comment]
I tried simplifying the bounding objects to keep only the two 'colliding' cylinders (to make sure it was not a collision with a 'hidden' bounding object), but the problem is still here:
![ur10e_collisionbugwbt_3](https://user-images.githubusercontent.com/2461619/93052211-f9b8f780-f665-11ea-9431-83d0cd59bf3e.png)

**Comment by westinsykes** [comment]
As a note, real UR arms treat that pose similarly to a collision in order to prevent people's fingers from getting pinched.

**Comment by omichel** [comment]
Fixed in #2282.
