### ISSUE TITLE
Wrong color blending when pen.inkdensity is not 1

### ISSUE THREAD

**Issue by DavidMansolino** [cyberbotics/webots#2353]
**Describe the Bug**
> when I set inkdensity to intermediate amounts, it seems to average the pen color with white, rather than with whatever the existing color of the surface is, so it looks bad on surfaces that aren't naturally near-white

This is reproducible in the `pen.wbt` sample.

The blending with the `WorldInfo.inkEvaporation` factor works fine, the inkdensity should work the same way.

**Screenshots**
![pen](https://user-images.githubusercontent.com/2461619/96407890-a8f76a00-11e2-11eb-9998-aa733aa77c0b.png)

**Additional context**

This is happenning both with Appearance and PBRAppearance.

**Comment by Justin-Fisher** [comment]
I dived into source code and diagnosed what's going on here.  The relevant file is https://github.com/cyberbotics/webots/blob/d019ad4906e44a34a94fbea4e110d71af7172c07/src/webots/nodes/utils/WbPaintTexture.cpp 

Several places (lines 91-97, and lines 131-137) "clear" a paintable texture by making it be "transparent white" (1,1,1,0).  My guess is that one of these is where the white in the "average with white" bug is coming from.  Lines 251-254 compute a weighted RGB average between the new ink that should be added and the old ink that is already there, with no regard to whether that old ink is transparent or opaque.  Since the old ink defaults to being transparent white (1,1,1,0), a weighted average between the new ink RGB and that old "white" ink RGB produces the "averaging with white" effect.

I think the best way to solve this is to actually make use of the alpha channel of your paint layer, rather than always setting it to 0 or 1 like you currently do.  That way all we have to do is mix old ink and new ink, and the alpha channel will let an appropriate amount of the underlying surface show through, much as it does as ink evaporates.

In the simple case where the current ink is fully transparent, the new pixel should just be the new ink's RGB with its density as the alpha (rather than averaging with the current "transparent white" ink color the way it currently does).  In the simple cases where there is already fully opaque ink there, the current calculation does a fine job of mixing the new low-density ink atop that old ink.  The trickier cases are all the inbetween cases.  E.g., what should happen if you paint over half-transparent red with half-transparent blue?

To answer this, let's assume that we're spraying tiny droplets of paint that randomly land on tiny subpixels too small to see, and whenever a new droplet covers an old one it fully hides the old one, and the alpha channel indicates what percentage of the surface actually gets hit with droplets.  Given those assumptions half-transparent blue (0,0,1,0.5) sprayed atop half-transparent red (1,0,0,0.5) should end up having sprayed 3/4 of the underlying surface, so the alpha would need to be 0.75, and 2/3 of that 3/4 will be blue, and only 1/3 will be red (with the remaining red having been covered by blue).  So the right new ink color, given these assumptions, should be (1/3,  0,  2/3,  3/4)

Putting this in general form (in pseudo code), we get the following suggested replacement for what is currently in lines 239-242 and 251-254. 
```
combinedInkOpacity = newInkOpacity + oldInkOpacity * ( 1 - newInkOpacity).

combinedInkColor = newInkColor * newInkOpacity / combinedInkOpacity + oldInkColor * oldInkOpacity * (1 - newInkOpacity) / combinedInkOpacity.
```
In addition I would suggest also adding "eraser" functionality for non-positive values of the Pen's density field, right in the same computation.

A crude eraser capacity would just use the allowable density of 0, which currently is just an elaborate way of adding 0 to things, and make that erase.  The following two lines of pseudocode would accomplish that:

```
if density==0 
    combinedInkOpacity = 0 
```

However, I think it would be better to let negative inkDensity subtract that fraction of existing ink (i.e. positive ink density indicates the fraction of the surface that will have ink added, whereas negative ink density indicates the fraction of the surface that will have ink subtracted).  So I would suggest instead using the following (pseudo) code to do that:
```
if density < 0 
    combinedInkColor = oldInkColor
    combinedInkOpacity = oldInkOpacity * (1 + density)
```
To get this to work, you might also need to change any part of the API that enforces the current requirement that density be in the range [0,1], extending this to [-1,1].
