### ISSUE TITLE
Streaming simulation over wss

### ISSUE THREAD

**Issue by yuchen93** [cyberbotics/webots#2633]
**Describe the Bug**
I am trying to stream a simulation with ssl connection but got an websocket 1006 error.

**Steps to Reproduce**
I started webots simulation on the server with the 'ssl' option in the 'streaming':
`xvfb-run webots --batch --mode=realtime --stdout --stderr --minimize --stream="port=1235;monitorActivity;mode=x3d;disableTextStreams;ssl" ./worlds/<world_file>`

I then used the streaming viewer.html file but changed ws to wss:
`view = new webots.View(document.getElementById("playerDiv"), 0);`
`view.open("wss://"+ip+":1235")`

**Expected behavior**
Before I setup ssl the ws version works so I expect the simulation streaming with wss to work the same as with ws. I have added the `cert.pem` file at `/home/ubuntu/webots/resources/web/server/ssl/cert.pem`.

**Screenshots**
![error message](https://user-images.githubusercontent.com/14132226/103807748-85db9a00-501c-11eb-87ea-4339a89cb893.png)

**System**
 - Operating System: Linux Ubuntu 18.04, AWS server

**Comment by omichel** [comment]
You also need to add the file `privkey.pem` in the same folder as `fullchain.pem`.

_Note_: to run Webots server over SSL, it is recommend (and easier) to use port rewrite instead of SSL configuration of Webots. This way, you can run Webots server in non-SSL mode and have your Apache server redirect SSL traffic to it, so that from a client perspective, everything works with SSL. This is explained [here](https://cyberbotics.com/doc/guide/web-simulation#port-rewrite).

**Comment by yuchen93** [comment]
Thanks! My problem has been resolved.
