### ISSUE TITLE
simulation_reset API doesn't work if PROTO contains LUA statements

### ISSUE THREAD

**Issue by ad-daniel** [cyberbotics/webots#2852]
**Describe the Bug**
Calling `wb_supervisor_simulation_reset()` does appear to reset the PROTO nodes, but afterwards they no longer move.

**Steps to Reproduce**
1. Download [bug_proto_reset.zip](https://github.com/cyberbotics/webots/files/6137226/bug_proto_reset.zip)

2. Notice that the robot contains a HingeJoint as well as a simple PROTO shown below (which is just another HingeJoint):
```
PROTO HingeJointInAProto [
  field SFNode     jointParameters   NULL 
  field MFNode     device            [ ] 
  field SFNode     endPoint          NULL  
]
{
  %{ }%

  HingeJoint {
    jointParameters IS jointParameters
    device IS device
    endPoint IS endPoint
  }
}
```
3. When you run it, the blue box (the PROTO-defined one) doesn't move anymore after the reset 
4. Comment the `%{ }%` line in the PROTO and rerun, now it moves after the reset.

NOTE: manually resetting from the interface works just fine, the problem arises only with the `wb_supervisor_simulation_reset()` call.

EDIT: the bug is present both in master and develop

**Expected behavior**
The presence of LUA statements (in this case even the lack of them) in the PROTO shouldn't affect the reset mechanism.

**Screenshots**

https://user-images.githubusercontent.com/44834743/111078366-5140fe80-84f5-11eb-8f45-c764e636cd54.mp4

https://user-images.githubusercontent.com/44834743/111078246-ca8c2180-84f4-11eb-9af8-ce895fd59984.mp4

**System**
 - Operating System: Ubuntu 20.04
 - Graphics Card: GeForce GT 730M

**Comment by omichel** [comment]
I believe this is not a bug, but a misleading feature.
Actually, adding the `static` tag fixes the problem.
This is due to the fact that resetting a non-static PROTO that will regenerate without restarting the corresponding controller is something very hazardous which should probably not be done because a non-static PROTO can completely change when regenerated (with the same parameters) and the corresponding controller may be unable to handle it (wrong devices handles, etc.).

So to make this feature less misleading, I would suggest to make all PROTOs static by default and remove the `static` tag. Instead a `nonStatic` tag should be introduced. Maybe `nonDeterministic` is a better name for this tag?
