### ISSUE TITLE
simulationReset() Doesn't work on conveyor and TV

### ISSUE THREAD

**Issue by Dorteel** [cyberbotics/webots#2866]
**Describe the Bug**
When using the supervisor's *simulationReset()* function, conveyor belts and TVs do not seem to reset.

**Steps to Reproduce**
1. Download the example world [simulation_reset_bug.zip](https://github.com/cyberbotics/webots/files/6151266/simulation_reset_bug.zip)
2. Use the following simple controller for the robot:
```
#!/usr/bin/env python3
from controller import Supervisor

counter = 0
supervisor = Supervisor()
robot_node = supervisor.getFromDef("UR3")

while supervisor.step(32) != -1:
    counter += 1
    if counter > 100:
        counter = 0
        supervisor.simulationReset()
```
**Here is how the simulation looks like**
![image](https://user-images.githubusercontent.com/16238582/111357717-d6f5b300-8689-11eb-8bcf-50ca51e6dcc9.png)

**Expected behavior**
The simulation resets just like when pressing the reset simulation button, meaning that the cans reset, the conveyor keeps moving, and the TV also displays an image.

**System**
 - Operating System: Linux Ubuntu 18.04
 - Graphics Card: GeForce RTX 2070

**EDIT**
Might be related to #2852

**Comment by omichel** [comment]
This is because both the TV and conveyor belt have a controller which you have to restart also from the supervisor.
When calling reset from the GUI, all controllers are automatically restarted.
When calling reset from a supervisor, you have to restart also the controllers from the same supervisor.
See https://cyberbotics.com/doc/reference/supervisor#wb_supervisor_simulation_reset
