### ISSUE TITLE
Copy paste an object on MacOS Catalina

### ISSUE THREAD

**Issue by ValerieMichel** [cyberbotics/webots#3054]
I am following Tutorial 1 of the User Guide, and want to duplicate the wooden box.
 ⌘ command-V does not work, nor Edit>Paste.
It works only with the contextual menu.

**Comment by ad-daniel** [comment]
I've tested on a mac with a virtual keyboard and on Valerie's computer (with a mac keyboard) and it appears to be working. The office's mac uses a standard keyboard and it also works, but you need to do `windows key + C` instead of `CTRL + C`, but I assume that depends on how you setup the bindings.
