### ISSUE TITLE
Simulation speed doesn't go back to normal once leaving generic robot window

### ISSUE THREAD

**Issue by JamesLePoidevin** [cyberbotics/webots#3164]
**Describe the Bug**
While using the dji mavic 2 pro in a ardupilot simulation and i've added a gimbal (not yet implemented in ardupilot).To test that it is correctly set I opened the Generic robot window to move the gimbal motors. The simu fps took a hit 0.8 -> 0.6. When i go to the rotationMotor view i go from 0.6 -> 0.1 or 0.2, even if I don't change anything when I leave the generic robot window my simu fps doesn't go back up

**Steps to Reproduce**
1. Using arduPilot with SITL [webots](https://github.com/ArduPilot/ardupilot/tree/master/libraries/SITL/examples/Webots) with this file : 
[pyramidMapReduced2.zip](https://github.com/cyberbotics/webots/files/6637298/pyramidMapReduced2.zip)
Press Play
2. launch ./libraries/SITL/examples/Webots/pyramids_dronePlus.sh 
3. Open generic robot window and go to Rotationnal motors
4. Exit the window and the fps doesn't go back to original 0.8

**Expected behavior**
Without enabling anything in the generic robot window the fps show go back to the original 0.8

**Screenshots**

https://user-images.githubusercontent.com/44805587/121663939-3c014f00-caa7-11eb-84f5-cbf794390830.mp4

**System**
 - Operating System:Linux Ubuntu 20.04
 - Graphics Card: GeForce GTX 750 Ti
 - ArduPilot : https://github.com/ArduPilot/ardupilot

**Comment by omichel** [comment]
Relates with #2655.

**Comment by stefaniapedrazzi** [comment]
I see from your video that you are using R2021a.
We improved the performance of the robot window in Webots R2021b.
Please try to install the latest nightly build of **Webots R2021b** and let us know if you can still reproduce this issue:
https://github.com/cyberbotics/webots/releases/tag/nightly_11_6_2021

It is expected that opening the robot window will make the simulation speed drop.
This also depends on the number of devices available on the selected tab of the robot window. For this reason, in R2021b we also added the option to disabled independently each plot (with or without disabling the corresponding device in the simulation) so that it is possible to enable just the needed plots with the minimal simulation speed drop.

**Comment by JamesLePoidevin** [comment]
Thank you for your reply that fixed the problem .
