### ISSUE TITLE
missing controller executable in sample world vision (draft build)

### ISSUE THREAD

**Issue by Thomas-Feldmeier** [cyberbotics/webots#3372]
sample world vision:

```
WARNING: vision: Could not find controller file:
WARNING: vision: Expected either: vision, vision.jar, vision.class, vision.py, or vision.m 

```

if i try to compile, it shows:

```
You are trying to modify a file located in the Webots installation directory:

'/usr/local/webots/projects/samples/howto/vision/controllers/vision'

This operation is not permitted: would you like to copy the necessary files to another location?

```
webots --sysinfo
System: Linux 5.8.0-59-generic x86_64
Processor: Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz
Number of cores: 4
OpenGL vendor: NVIDIA Corporation
OpenGL renderer: GeForce GTX 1050/PCIe/SSE2
OpenGL version: 4.6.0 NVIDIA 450.119.03
webots --version
Webots version: R2021b
(draft version from jul 7 16:20; same error happens in night_build from yesterday)

cd

**Comment by omichel** [comment]
Thank you for the tests!
However, this vision controller is not included on purpose. This is because it has a dependency on opencv which we don't want to include in Webots to minimize the size of the Webots package. Therefore this example is provided as source only and users who want to use it need to install opencv in order to be able to compile it.
