### ISSUE TITLE
Is it "SolidReference" BUG 

### ISSUE THREAD

**Issue by chinahuangyong** [cyberbotics/webots#3497]
when i use the "SolidReference",  but it .....
![2021 07 22_webots](https://user-images.githubusercontent.com/20627061/126819373-22f43972-4541-44b2-b31d-b43ce33ca671.gif)

**Comment by chinahuangyong** [comment]
This is my project
[stdbot_sim.zip](https://github.com/cyberbotics/webots/files/6870368/stdbot_sim.zip)

**Comment by ShuffleWire** [comment]
When working on an issue, first try to explain which result you expect "when i use the "SolidReference", but it ....." is not enough as issue ;) 
AFAIK, it should create a joint to close the loop, but it fall of as being not properly anchored
Secondly try to provide the smallest example that show the issue. For of, if the problem is not related to the contoler, remove it. And try to provide the smallest model possible.
I've made that, at least a first version, so others could take a look.
[stdbot_sim.zip](https://github.com/cyberbotics/webots/files/6872955/stdbot_sim.zip)

**Comment by chinahuangyong** [comment]
think you, got it ,and this is a success gif

**Comment by chinahuangyong** [comment]
![2021 07 22_webots_ok](https://user-images.githubusercontent.com/20627061/126928294-96cb4abb-aab0-4f50-9e35-471a20a36855.gif)
