### ISSUE TITLE
ENU conversion: Viewpoint rotation bug

### ISSUE THREAD

**Issue by ad-daniel** [cyberbotics/webots#3570]
**Describe the Bug**
This bug concerns the `feature-enu-plan` branch.

How to reproduce:
1. open `tests/protos/template_proto_with_nested_template_parameter_1.wbt`
2. select `TempalteProtoWithRegeneratingTemplateParameter` node
3. do `alt+F5` to move viewpoint to the object
4. Whether the mouse is moved vertically or horizontally, the rotation of the viewpoint is the same.

**Comment by stefaniapedrazzi** [comment]
This error is not a regression due to the conversion to ENU but was already there before (just occurring with a different setup).
It occurs when the world up axis is parallel to the viewpoint right axis.

Moving the mouse left-right should always correspond to rotating the viewpoint along the world up axis independently from the current viewpoint orientation (this is behavior implement in all the 3D tools, like Blender, etc.).

This problem is a very special case and it is a consequence of Webots supporting tilting the viewpoint (not available for example in Blender) but the behavior is correct even if it seems wrong.

Rather that changing the behavior, we can add more details in the documentation so that it would be more clear why this special case occurs.
