### ISSUE TITLE
HTML5 animation export failed for forest_firefighters.wbt

### ISSUE THREAD

**Issue by joachimhgg** [cyberbotics/webots#3986]
**Describe the Bug**
Close Webots and display this error:
`nodes/WbGeometry.cpp:626: virtual void WbGeometry::exportBoundingObjectToX3D(WbVrmlWriter&) const: Assertion 'mWrenMesh' failed.`

This issue is related to the function `WbWorld::write`.
Present in #feature-enu-plan at least since the 6th of October 2021.

**Steps to Reproduce**
1. Open `forest_firefighters.wbt` ([from webots-project](https://github.com/cyberbotics/webots-projects))
2. Click on 'Start HTML5 animation recording...'
3. Save your file

**Comment by omichel** [comment]
The crash occurs only with the unmodified world from R2021b.
After updating this world to R2022a, it doesn't crash any more.
The crash is due to the fact that the `ElevationGrid` misses the `yDimension` (it has zDimension` instead) and hence it sets `yDimension` to `1` (its default value). However an `ElevationGrid` with a `yDimension` of 1 is unable to generate a bounding object and a warning is displayed about this. When trying to export we assume the bounding object was properly generated which is not the case and hence the crash. It should be easy to fix. I am on it.
