### ISSUE TITLE
Crashed when loading a world created by 2020b.

### ISSUE THREAD

**Issue by zapplelove** [cyberbotics/webots#4431]
Here is my robot world created by webots version 2020b:
[world.zip](https://github.com/cyberbotics/webots/files/8416336/world.zip)
and when I want to load it using the latest version, app crashed.

**Comment by ad-daniel** [comment]
Since R2022a  there have been significant changes to the orientation of robots/worlds, so in order be able to open it with this version requires adapting your world, more details are available here: https://github.com/cyberbotics/webots/wiki/How-to-adapt-your-world-or-PROTO-to-Webots-R2022a

When loading a world, Webots reads the headers of protos and worlds (i.e something like `#VRML_SIM R2020b utf8`) and if it has been created with a version prior to R2022a it will attempt to do some of the necessary adjustments itself (not everything). There's no guarantee everything will work afterwards but it shouldn't crash either so I will investigate it. However in your case it might be faster to create a new world in R2022a, the robot appears to be in the correct orientation already (don't forget to change the header in the proto however), meaning you probably only need to adapt the conveyor belt (of which you could use the one provided in Webots `ConveyorBelt`)

**Comment by zapplelove** [comment]
Thanks a lot. I have changed the `belt.proto` using the one provided in Webots ConveyorBelt, and it worked. 

> By the way, because I am Chinese, I can't get `resources` online when using webots, I have to compile it. So is it possible to use local resources instead of online？
