### ISSUE TITLE
macOS darwin-op robot window not working

### ISSUE THREAD

**Issue by ThomasOliverKimble** [cyberbotics/webots#4824]
**Describe the Bug**
The darwin-op robot window does not open, most of the time with no error, but sometimes gives the following error:

```
Error: dlopen(/Applications/Webots.app/Contents/projects/robots/robotis/darwin-op/plugins/robot_windows/robotis-op2_window/librobotis-op2_window.dylib, 9): Library not loaded: @rpath/Contents/Frameworks/QtCore.framework/Versions/A/QtCore
  Referenced from: /Applications/Webots.app/Contents/projects/robots/robotis/darwin-op/plugins/robot_windows/robotis-op2_window/librobotis-op2_window.dylib
  Reason: image not found (dynamic library)
Error: robot window initialization failed
Error: Cannot load the "/Applications/Webots.app/Contents/projects/robots/robotis/darwin-op/plugins/robot_windows/robotis-op2_window/librobotis-op2_window.dylib" robot window library.
```

**Comment by omichel** [comment]
It could probably be fixed in the `runtime.ini` file of the robot controllers.

**Comment by BenjaminDeleze** [comment]
My bad, I made a mistake in my previous tests:
- all worlds from the .dmg are broken
- but if I open a world that is in the development environment with the dmg, it works.
- everything works fine in the development environment.

Some times the robot windows does not open (wether it should bug or load correctly) and there is no errors. It always happen when the simulation is running. I have the feeling that it is because the mac is struggling to run the simulation at real-time. Because if I pause, the "normal" behaviour happens (error or correct display)
