### ISSUE TITLE
Search for Webots tmp directory in libController is not robust

### ISSUE THREAD

**Issue by stefaniapedrazzi** [cyberbotics/webots#5300]
If a snap installation of Webots is found on the system but another Webots (git clone, tarball, or debian) version is currently executed, the libController uses the snap `tmp` directory for connecting extern controllers and fails to connect instead of checking if the Webots instance files exists and reverting to the system `tmp` folder.

**Comment by ygoumaz** [comment]
I can't reproduce this issue.

Here are the steps I applied:
1. I installed the snap version of Webots.
2. Executing `which webots` outputs `/snap/bin/webots`.
3. I then start Webots installed from sources.
4. I set the controller field of a robot of the simulation to `<extern>`. 
5. When trying to execute a controller in another terminal, the controller correctly connects to the robot.

Also if no Webots instance is running, the error message given by the libController is the following.
```bash
Cannot connect to Webots instance on socket "/tmp/webots-1234/ipc/MyBot/extern", retrying for another 50 seconds...
```

Can you still reproduce this issue?

**Comment by stefaniapedrazzi** [comment]
I don't recall exactly in which system I was reproducing it and how.

However, I could still reproduce this under the following conditions.
I used the `languages/python/worlds/example.wbt` and changed the first slave robot controller to extern (I also copied the driver common module to slave controller to simplify the setup).

Steps:
1. Start Webots from tarball installation on port 1234 (path `~/Downloads/webots-R2023a/webots/`) and run example simulation
2. Start Webots from snap on port 1235 (so that a webots-1234 file is created in the tmp folder) and run example simulation
3. In a terminal set the WEBOTS_HOME to the tarball and `WB_CONTROLLER_URL=ipc://1234/robot1`
4. Start the extern controller that should connect to Webots from tarball (port 1234):
    ```sh
   export WEBOTS_HOME=~/Downloads/webots-R2023a/webots
   export PYTHONPATH=${WEBOTS_HOME}/lib/controller/python
   export WEBOTS_CONTROLLER_URL="ipc://1234/robot1"
   python3 slave.py
    ```

Error message:
```
Cannot connect to Webots instance on socket "/home/stefi/snap/webots/common/tmp/webots-1234/ipc/robot1/extern", retrying in 0 second...
```

As expected I have these Webots tmp folders and files:
* `/home/stefi/snap/webots/common/tmp/webots-1235/ipc/robot1/extern`
* `/tmp/webots-1234/ipc/robot1/extern`

But the correct Webots tmp folder is not found.


Note that in case Webots was not properly closed the `webots-<pid>` temp folder could also remain (this should be cleanup when Webots is restarted).

**Comment by ygoumaz** [comment]
I can now reproduce the issue by following your exact steps. I will investigate it.

**Comment by ygoumaz** [comment]
I investigated a little and found out the origin of the bug.

In the [wbu_system_tmpdir() function](https://github.com/cyberbotics/webots/blob/master/src/controller/c/system.c#L87-L133), the tmp dir is first set to `WEBOTS_TMPDIR`. I don't know when this environment variable is set but in case of extern controllers it is never set and is empty.
If empty, it then sets it to the tmp dir of the snap Webots instance (if running). This is the cause of the reported bug. If no snap instance is running (in general), it is set to `/tmp` and it works fine.
**So the exact issue is the following: when multiple Webots instances run and some of them are snap and some not, it is impossible to target the normal instance with `WEBOTS_CONTROLLER_URL` because the snap tmp dir will always be used.**

I think @omichel took care a while ago to rename and refactor this tmp dir part. `wbu_system_tmpdir()` is only executed (from `robot.c`) when running extern controllers (never for intern ones I believe), so I don't really understand the point to use the `WEBOTS_TMPDIR` variable environment variable. Should it be set by the user? Or should we set it in the new extern controller launcher?

Alternatively, I wonder if this whole part should not be refactored to compute the tmp dir path from the `WEBOTS_HOME` set by the user. I believe we could check in `WEBOTS_HOME` if the target local Webots instance is snap or not and adapt the tmpdir accordingly in this case.

Any thoughts?

**Comment by omichel** [comment]
Yes, I believe it makes more sense to get rid of this `WEBOTS_TMPDIR` variable on the libController side and compute the system tmp directory based on the value of `WEBOTS_HOME` which should contain a path telling us whether this is the snap version of Webots we are using or not.
