### ISSUE TITLE
Webots crash on save

### ISSUE THREAD

**Issue by raysworld** [cyberbotics/webots#5677]
**Describe the Bug**
Webots crashes every time I click on 'save' button.

**Steps to Reproduce**
1. Open a random .wbt file.
2. Change whatever to make save button enabled. 
3. Click on save button
4. The .wbt file is saved but webots crashes with the following output:
   ```shell
   /usr/local/bin/webots: line 102: 27101 Aborted                 (core dumped) "$webots_home/bin/webots-bin" "$@"
   ```

**Expected behavior**
The wbt file is saved and Webots does not crash

**Screenshots**
Please see [here](https://youtu.be/PgOZ7V2GzdY)

**System**
 - Operating System: Ubuntu 20.04 LTS, Ubuntu 22.04 LTS
 - Graphics Card: NVIDIA GeForce RTX 3050 Ti
 - Laptop: ROG Flow 13

**Comment by stefaniapedrazzi** [comment]
This bug seems very specific to your environment.
Something strange occurs because you should not be allowed to save the world inside the Webots installation directory (`\usr\local\webots` is not writable) and instead a dialog should pop asking to relocate the project.

Could you run this command in the terminal where you start Webots and post the result?
```sh
printenv | grep "WEBOTS"
```

If you install Webots using the tarball package do you get the same issue?
https://github.com/cyberbotics/webots/releases/download/R2023a/webots-R2023a-x86-64.tar.bz2

**Comment by stefaniapedrazzi** [comment]
Can you try to install Webots from this archive and run it?
Tarball file: https://github.com/cyberbotics/webots/suites/9964555402/artifacts/483027602
Debian file: https://github.com/cyberbotics/webots/suites/9964555402/artifacts/483027603

This version of Webots R2023a is compiled in debug mode so it will give us more information about the crash.
After installing you should open a terminal and type:
```sh
export WEBOTS_HOME=~/Downloads/webots   # or your path to the Webots installation directory
export LD_LIBRARY_PATH=$WEBOTS_HOME/lib/webots
cd $WEBOTS_HOME
gdb bin/webots-bin
```
The when GDB starts your should simply type `r` in the terminal (GDB console).
Once Webots crashes, could you please type `bt` in the terminal (GDB console) and copy here the output?

**Comment by stefaniapedrazzi** [comment]
Closing inactive issue.
