### ISSUE TITLE
Displays in extension slots cause warnings

### ISSUE THREAD

**Issue by ad-daniel** [cyberbotics/webots#5842]
**Describe the Bug**

1. Open the `jetbot.wbt` world
2. Add a `Display` node to the `extensionSlot`
3. Save & reload, a warning is printed 
```
WARNING: DEF JETBOT JetBot (PROTO) > DEF BODY Transform > DEF DISPLAY Transform > Display: 'name' field value should be unique: 'display' already used by a sibling Solid node.
WARNING: DEF JETBOT JetBot (PROTO) > Display: 'name' field value should be unique: 'display' already used by a sibling Solid node.
```
4. Two display entries are also shown under `Overlay > display devices`

Although there is only one instance of the node, multiple are detected. I supposed because it's a PROTO parameter.

**Comment by stefaniapedrazzi** [comment]
The error is correct.
The problem is not that there is multiple instances of the node, but that the JetBot PROTO already contains in body a Display device called "display" and both nodes have the same Solid ancestor.
When searching for siblings Transform and Group nodes are expanded but "ignored" as parent. 

However, the error should be printed just after inserting the new Display in the `extensionSlot` and not only after reloading.
