### ISSUE TITLE
Improve TIAGo model

### ISSUE THREAD

**Issue by stefaniapedrazzi** [cyberbotics/webots#6046]
Update the TIAGo model to the latest PAL Robotics version:
* [x] add a custom RGB-D camera (specifications https://shop.orbbec3d.com/Astra-S)
* [x] change name of models from iron/steel/etc. to "TIAGo lite" (no arms), "TIAGo" (1 arm + gripper) and TIAGo ++ (2 arms + gripper)
* [ ] Add TIAGo omni base
* [x]  Add TIAGo robotiq grippers

**Comment by thomaspeyrucain** [comment]
Hello Webots team,

The robotiq models are missing the coupling link that PAL added to interface the robotiq gripper with the arm of the robot

![image](https://github.com/cyberbotics/webots/assets/87322480/101518c1-66ab-427f-b0ca-6208370e53ea)

**Expected behavior**
The gripper should look like that for all robotiq gripper equipped on TIAGo:
![image](https://github.com/cyberbotics/webots/assets/87322480/88262970-de6b-47b7-811d-486dc9bbc482)

You can find the model for the coupling link here:
- [With eletronics](https://github.com/pal-robotics/pal_robotiq_gripper/blob/master/pal_robotiq_85_gripper/pal_robotiq_85_description/meshes/visual/pal_robotiq_coupling.stl)
- [Without electronics](https://github.com/pal-robotics/pal_robotiq_gripper/blob/master/pal_robotiq_140_gripper/pal_robotiq_140_description/meshes/visual/pal_robotiq_coupling.stl)

And in [this urdf](https://github.com/pal-robotics/pal_robotiq_gripper/blob/master/pal_robotiq_85_gripper/pal_robotiq_85_description/urdf/robotiq_85_gripper.urdf.xacro#L293)

The coupling link stl model is the same for the 3 robotiq grippers

**Affected Packages**
List of affected packages:
  - [projects/devices/robotiq/protos/Robotiq2f85Gripper.proto](https://github.com/cyberbotics/webots/blob/8aba6eaae76989facf3442305c8089d3cc366bcf/projects/devices/robotiq/protos/Robotiq2f85Gripper.proto#L96)
  - [projects/devices/robotiq/protos/RobotiqEPickGripper.proto](https://github.com/cyberbotics/webots/blob/8aba6eaae76989facf3442305c8089d3cc366bcf/projects/devices/robotiq/protos/RobotiqEPickGripper.proto)
  - [projects/devices/robotiq/protos/Robotiq2f140Gripper.proto](https://github.com/cyberbotics/webots/blob/8aba6eaae76989facf3442305c8089d3cc366bcf/projects/devices/robotiq/protos/Robotiq2f140Gripper.proto)


**System**
 - Webots Version: R2023b
 - ROS Version: Humble
 - Operating System: Linux Ubuntu 20.04
 - Graphics Card: Nvidia

**Comment by thomaspeyrucain** [comment]
We also updated the stl of the omni_base to remove the unnecessary inside components [here](https://github.com/pal-robotics/omni_base_robot/blob/melodic-devel/omni_base_description/meshes/base/base_link.stl):
![image](https://github.com/cyberbotics/webots/assets/87322480/85ac32a8-9a31-47dd-98ce-6000f01d0e22)

**Comment by BenjaminDeleze** [comment]
Dear @thomaspeyrucain,

I added the couple link to the robotiq grippers, you can check it in [this PR](https://github.com/cyberbotics/webots/pull/6401)

However, I am affraid we will not be able to use the new mesh you provided for the omni_base as it does not meet the Webots quality standard:
  - The mesh is still to big: in Webots no mesh should exceed 21845 triangles. Dividing a large mesh into several smaller ones is a possible solution, but simplifying each mesh should be done whenever possible.
  - Also, the mesh contains some artifacts like on the picture below.

![tiago_omni_base](https://github.com/cyberbotics/webots/assets/25938827/fad4ecc8-a97c-4aed-a5f3-ecf9c101ad39)

**Comment by thomaspeyrucain** [comment]
Hello @BenjaminDeleze ,
Thank you I will see internally what we can do about this
