### ISSUE TITLE
Issues with Travis and OpenAL library

### ISSUE THREAD

**Issue by fabienrohrer** [cyberbotics/webots#964]
In a justified way, @omichel tried to simplify the OpenAL dependency on Linux. Unfortunately, `Travis` seems to break this dependency when creating the tar.bz2 file. We had to revert this patch for the `R2019b.rev1` release, but it would be interesting to dig further in this direction: https://github.com/cyberbotics/webots/pull/963

**Comment by fabienrohrer** [comment]
The #963 patch doesn't work. The issue is still present on revision.

**Comment by stefaniapedrazzi** [comment]
I just created a test package on Ubuntu 18.04 after a `make cleanse` and I get the exact same issue with `libopenal.so.1` with the package generated locally. So maybe it is not just an issue specific to Travis.

**Comment by stefaniapedrazzi** [comment]
The issue is simply that the soft link path is not created as relative path, i.e. the path is set to  `$(WEBOTS_HOME)/lib/libopenal.so` instead of `libopenal.so`.

A `cd` into the `lib` folder before creating the soft link should fix the issue.
But it seems there is also the `-r` (or `--relative`) `ls` option that should do the same.

https://superuser.com/questions/146231/how-do-i-create-a-relative-symbolic-link-in-linux
